import { importDocumentFile, listDocuments, searchDocuments, deleteDocument, getDocumentStats } from '../documentService.js';
import { linkEntities, getEntityConnections } from '../relationships.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const fmt=n=>n?`${Math.round(n/1024)} KB`:'—';
export async function render(mount){
  mount.innerHTML=`<section class="canvas__header"><p class="canvas__eyebrow">Library</p><h1 class="canvas__title">Files & Documents</h1><p class="canvas__dek">Keep church and ministry documents local, searchable, and connected to the work where they are used.</p></section>
  <section class="workspace-grid"><article class="panel"><div class="panel__head"><div><h2>Document Cabinet</h2><p class="muted">Import PDF, TXT, Markdown, HTML, or JSON text documents.</p></div><label class="button primary" for="document-file">Import file</label><input id="document-file" type="file" accept=".pdf,.txt,.md,.markdown,.html,.htm,.json,application/pdf,text/plain,text/markdown,text/html,application/json" hidden></div><div class="toolbar"><input id="document-search" class="field" placeholder="Search files and document text…"><span id="document-stats" class="muted"></span></div><div id="document-results" class="stack"></div></article><aside class="panel"><h2>How this works</h2><ul class="plain-list"><li>Files stay in your local Workbench database.</li><li>Readable text is indexed for Universal Search and AI retrieval.</li><li>Documents can be linked to projects, sermons, lessons, and studies.</li><li>The original source remains separate from your personal notes.</li></ul><div id="document-message" class="status-panel" hidden></div></aside></section>`;
  const search=mount.querySelector('#document-search'), results=mount.querySelector('#document-results'), msg=mount.querySelector('#document-message');
  const stats=mount.querySelector('#document-stats');
  async function refresh(q=''){
    const docs=await listDocuments(q); const st=await getDocumentStats(); stats.textContent=`${st.documents} file${st.documents===1?'':'s'} • ${st.chunks} searchable chunks`;
    results.innerHTML=docs.length?docs.map(d=>`<article class="knowledge-card"><div class="knowledge-card__head"><div><h3>${esc(d.title)}</h3><span class="pill">${esc(d.mime_type||'document')}</span> <span class="muted">${esc(fmt(d.file_size))}</span></div><button class="text-button danger" data-delete="${esc(d.id)}">Delete</button></div><p>${esc(d.description||d.filename||'Local ministry document')}</p><div class="toolbar"><input class="field" data-doc-search="${esc(d.id)}" placeholder="Search inside this file…"><button class="text-button" data-search-doc="${esc(d.id)}">Find</button></div><div data-doc-hits="${esc(d.id)}"></div></article>`).join(''):'<div class="empty-state">No documents yet. Import a church document, PDF, or study file to begin.</div>';
    results.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this document from Workbench?'))return;await deleteDocument(b.dataset.delete);await refresh(search.value);});
    results.querySelectorAll('[data-search-doc]').forEach(b=>b.onclick=async()=>{const q=results.querySelector(`[data-doc-search="${CSS.escape(b.dataset.searchDoc)}"]`)?.value||'';const hits=await searchDocuments(q,{limit:6,documentId:b.dataset.searchDoc});const box=results.querySelector(`[data-doc-hits="${CSS.escape(b.dataset.searchDoc)}"]`);box.innerHTML=hits.length?hits.map(h=>`<div class="search-hit"><strong>Chunk ${h.index+1}</strong><p>${esc(h.content.slice(0,500))}</p></div>`).join(''):'<p class="muted">No matches.</p>';});
  }
  search.oninput=()=>refresh(search.value);
  mount.querySelector('#document-file').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;msg.hidden=false;msg.textContent=`Importing ${file.name}…`;try{await importDocumentFile(file);msg.textContent='Imported successfully.';await refresh(search.value);}catch(err){msg.textContent=err.message||String(err);}finally{e.target.value='';}};
  await refresh();
}
